theme: jekyll-theme-primer
logo: https://ynwd.github.io/catatan/images/roadway.jpg
google_analytics: UA-23287152-4
title: catatan
description: Koleksi catatan programming. Disusun berdasarkan skala prioritas dan tingkat kesulitan
